// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712230028_AddUserAvatarUrl")]
    partial class AddUserAvatarUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.Entities.FavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("UserId", "SpotId")
                        .IsUnique();

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SurfedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("UserId");

                    b.ToTable("surf_sessions", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSpotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentWaveSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Facilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MaxWaveSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinSkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinWaveSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SuitableBoardTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TypicalCrowd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("surf_spots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Raglan's long sandy beach break. Consistent, gentle waves and lifeguard patrol make it the go-to beginner spot on the West Coast.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "Rentals", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Ngarunui Beach",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Raglan's iconic left-hand point break — one of the longest in the Southern Hemisphere. A bucket-list wave that draws surfers from around the world.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Manu Bay",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Longboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "The Mount's main beach is a long, approachable beach break with excellent facilities. A great all-rounder spot suitable for every level.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Rentals", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Mount Maunganui",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "Waikanae Beach sits right in town and offers mellow, learner-friendly waves backed by full beach facilities.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Rentals", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Gisborne Town",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A cobblestone right-hander just north of Gisborne. Quieter than the town beach with fun point break walls on a good swell.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Makorori Point",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Longboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Tucked beside Sumner, Scarborough picks up solid South Island swells and offers punchy beach break waves in a scenic setting.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Scarborough",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A reliable North Auckland beach break that delivers consistent surf and is usually less hectic than the city breaks.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Mangawhai Heads",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "AnkleHigh",
                            Description = "A long, sheltered beach just north of Auckland city with gentle, rolling waves — ideal for beginners and longboarders.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "Lifeguard" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Orewa Beach",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A popular holiday beach north of Auckland that picks up decent swells and serves up fun beach break peaks across its length.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Omaha",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A tucked-away beach inside a conservation area north of Mangawhai. Worth the walk in for quality, uncrowded waves.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Te Arai",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "An Auckland beach break that rewards those who make the effort with uncrowded, quality waves away from the main beaches.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Forestry",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Auckland's wild black-sand West Coast beach. Powerful and consistent with strong rips — rewarding for surfers with solid ocean awareness.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Muriwai",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Auckland's most famous surf beach — powerful, dramatic, and stunning. Heavy rips demand solid ocean experience before paddling out.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Piha",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "Inside a protected regional park on the Tawharanui Peninsula. A peaceful beach break with low crowds and a campground for an overnight trip.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Tawharanui",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Longboard", "Funboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A long, welcoming Bay of Plenty beach break. Consistent and forgiving — good for beginners and longboarders making the most of summer.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Waihi Beach",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A pretty Coromandel beach break with fun, manageable waves — popular with holidaying families and surfers looking for a chill session.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Pauanui",
                            Region = "Coromandel",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "One of the Coromandel's most popular surf towns. Peaks fire up and down the beach and it's at its best during an easterly swell.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Whangamata",
                            Region = "Coromandel",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "AnkleHigh",
                            Description = "A sheltered Northland cove with mellow, beginner-friendly waves and a relaxed holiday vibe.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Waipu Cove",
                            Region = "Northland",
                            SuitableBoardTypes = new List<string> { "Longboard", "Funboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "DoubleOverhead",
                            Description = "One of New Zealand's longest left-hand point breaks, near Ahipara at the foot of Ninety Mile Beach. Remote and raw — a reward for the committed.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Shipwreck Bay",
                            Region = "Northland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "A dramatic black-sand beach tucked in a valley west of Auckland. Powerful beach break that rewards those who respect its conditions.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Bethells Beach",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A hidden gem near Tutukaka in Northland. Sandy bottom beach break that rarely gets crowded — worth tracking down.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Sandy Bay",
                            Region = "Northland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A long, walling left-hand reef break near Oakura. One of Taranaki's most consistent and rewarding waves — best at solid swell with a light offshore.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Stent Road",
                            Region = "Taranaki",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A mellow reef break in Taranaki that turns on when other spots are too big. A local favourite that stays quiet even on good days.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Kumara Patch",
                            Region = "Taranaki",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "The main surf break in New Plymouth, breaking over a mix of reef and sand beneath the volcanic headland. Punchy and powerful when it lines up.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Back Beach",
                            Region = "Taranaki",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A reef break sitting just off Takapuna Beach on Auckland's North Shore. Can produce surprisingly good waves when the swell direction lines up.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Takapuna Reef",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A lesser-known Auckland reef that rewards those in the know with uncrowded, hollow waves when conditions align. Worth checking on a small easterly swell.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Daniels Reef",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A long sandy beach just north of Gisborne city with consistent beach break peaks. Popular with locals and a reliable option when the easterly swells arrive.",
                            Facilities = new List<string> { "Bathrooms", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Wainui Beach",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A powerful left-hand reef break tucked below the Kaikoura mountains. Named after the old meatworks nearby — raw, heavy, and stunning when it's firing.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Meatworks",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "One of New Zealand's longest right-hand point breaks, walling for hundreds of metres along the Kaikoura coastline. A remote gem that makes the drive from Christchurch very worthwhile.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Mangamaunu",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Longboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A hidden bay east of Sumner with rocky headland rights that reward surfers willing to make the hike from the car park. One of Canterbury's most scenic and consistent breaks.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Taylor's Mistake",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A long, sandy stretch east of Whakatane with mellow beach break peaks and plenty of space. One of the Bay of Plenty's quietest surf beaches — ideal for beginners wanting room to learn.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "Lifeguard", "Campground" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Ohope Beach",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A sheltered harbour-mouth beach break on the Coromandel's east coast that picks up east and northeast swells well. A reliable option when the west side is flat.",
                            Facilities = new List<string> { "Bathrooms", "SurfClub" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Tairua",
                            Region = "Coromandel",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Wellington's most accessible surf beach, right next to the airport. Consistent swell from Cook Strait makes it reliable year-round, though it fires best on calm mornings before the afternoon northerly kicks in.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard", "Rentals" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Lyall Bay",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "A dramatic lighthouse bay on the Wairarapa coast, two hours from Wellington. A reef break that fires with powerful East Coast swells — the remote setting and iconic scenery make the drive very much worth it.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Castlepoint",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A raw, wind-exposed beach break on Wellington's rugged west coast. Gets open-ocean swell that rarely reaches Lyall Bay — worth the extra drive when conditions align and the wind is light.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Makara Beach",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Dunedin's iconic surf beach at the foot of the Otago Peninsula. Reliable Southern Ocean swells, a surf club that's been running for over a century, and a famous saltwater hot pool right on the beachfront.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard", "Rentals" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "St Clair Beach",
                            Region = "Otago",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Dunedin's quieter neighbour to St Clair, sharing the same reliable Southern Ocean swells on a long exposed beach with consistent peaks. A good choice when St Clair is too busy.",
                            Facilities = new List<string> { "Bathrooms", "SurfClub" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "St Kilda",
                            Region = "Otago",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("TikTokHandle")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.UserPreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("BoardTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CrowdTolerance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PreferredFacilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PreferredRegion")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PreferredWaveSizes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("PreferredWaveTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.FavoriteEntity", b =>
                {
                    b.HasOne("Backend.Database.Entities.SurfSpotEntity", "Spot")
                        .WithMany("Favorites")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Entities.UserEntity", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSessionEntity", b =>
                {
                    b.HasOne("Backend.Database.Entities.SurfSpotEntity", "Spot")
                        .WithMany("SurfSessions")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Entities.UserEntity", "User")
                        .WithMany("SurfSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.UserPreferencesEntity", b =>
                {
                    b.HasOne("Backend.Database.Entities.UserEntity", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Backend.Database.Entities.UserPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSpotEntity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("SurfSessions");
                });

            modelBuilder.Entity("Backend.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Preferences");

                    b.Navigation("SurfSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
