// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728002752_MultiRegionSupport")]
    partial class MultiRegionSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.Entities.FavoriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("UserId", "SpotId")
                        .IsUnique();

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SurfedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("UserId");

                    b.ToTable("surf_sessions", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSpotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentWaveSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Facilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MaxWaveSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinSkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinWaveSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SuitableBoardTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TypicalCrowd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("surf_spots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b283513-697e-4a41-aaf5-c9c1c4eacaff"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Raglan's long sandy beach break. Consistent, gentle waves and lifeguard patrol make it the go-to beginner spot on the West Coast.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "Rentals", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Ngarunui Beach",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("e997bc0f-4267-423f-b018-300f2ab68238"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Raglan's iconic left-hand point break — one of the longest in the Southern Hemisphere. A bucket-list wave that draws surfers from around the world.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Manu Bay",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Longboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("83c3e03b-6c53-4d56-8459-e3b93e9c510f"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "The Mount's main beach is a long, approachable beach break with excellent facilities. A great all-rounder spot suitable for every level.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Rentals", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Mount Maunganui",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("d972655c-fd80-48b2-a9d5-843e8dcbd153"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "Waikanae Beach sits right in town and offers mellow, learner-friendly waves backed by full beach facilities.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Rentals", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Gisborne Town",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("fe120869-eb8b-4962-bf24-d9e83a3ef3fe"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A cruisy right-hand cobblestone point just north of Gisborne — long, fat shoulders ideal for cruising and carving. Sister break to North Makorori Reef across the bay. Gets busy on good days but localism is rare for New Zealand; best on a solid SE swell with a light offshore.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Makorori Point",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Longboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("5461358c-f193-4e36-82a0-ad5da43909ae"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Arguably Christchurch's single best surf spot — a right-hand point that peels from the headland over 100 metres into the bay, protected from easterlies by cliffs and a breakwater. Soft and mellow waves make it a longboarder's dream, while bigger winter swells bring out the performance surfers.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Scarborough",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Longboard", "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("c08fa569-6643-4842-b5a7-1349659a41cb"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A reliable North Auckland beach break that delivers consistent surf and is usually less hectic than the city breaks.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Mangawhai Heads",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("99d031a1-bed7-44b3-8217-5089e335c396"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "AnkleHigh",
                            Description = "A long, sheltered beach just north of Auckland city with gentle, rolling waves — ideal for beginners and longboarders.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "Lifeguard" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Orewa Beach",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("5b8a8775-d285-4c8d-b4c7-e9410f8cc698"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A popular holiday beach north of Auckland that picks up decent swells and serves up fun beach break peaks across its length.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Omaha",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("2f3b5dc5-36a7-4069-a349-91ab4af657fc"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A tucked-away beach inside a conservation area north of Mangawhai. Worth the walk in for quality, uncrowded waves.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Te Arai",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("88334bce-7cd9-42cd-8ae9-85f4bf2b71fc"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "An Auckland beach break that rewards those who make the effort with uncrowded, quality waves away from the main beaches.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Forestry",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("a369bf4f-1c77-4a5c-848c-f136d5b866c7"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Auckland's most powerful West Coast beach break, taking the full force of Tasman Sea swells. Sucky, punchy peaks reward experienced surfers — strong rips make it unsuitable for beginners. Check Maori Bay just around the headland for slightly more sheltered lefts and rights when Muriwai closes out.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Muriwai",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("a539f8d9-e30b-43ef-be31-529f991693b9"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Auckland's most iconic surf beach — one of the best on the North Island's West Coast. Sucky beach break with excellent lefts and rights off Lion Rock, set against dramatic black-sand cliffs. Heavy rips and powerful shore dump demand solid ocean experience; beginners should surf between the flags only.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Piha",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("5471f752-5f17-44f9-b0fb-b5a5adfa07c6"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "Inside a protected regional park on the Tawharanui Peninsula. A peaceful beach break with low crowds and a campground for an overnight trip.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Tawharanui",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Longboard", "Funboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("df46bcbe-0ebc-4910-a112-1e3bc0471559"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A long, welcoming Bay of Plenty beach break. Consistent and forgiving — good for beginners and longboarders making the most of summer.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Waihi Beach",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("9fad49c3-00c3-46a1-893c-88349b410a41"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A pretty Coromandel beach break with fun, manageable waves — popular with holidaying families and surfers looking for a chill session.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Pauanui",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("a8de5b53-30d6-4558-a690-71bafa56acc0"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "One of the Coromandel's most popular surf towns. Peaks fire up and down the beach and it's at its best during an easterly swell.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Whangamata",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("e28a0c71-4b34-4544-9f33-19c941bc1375"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "AnkleHigh",
                            Description = "A sheltered Northland cove with mellow, beginner-friendly waves and a relaxed holiday vibe.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Waipu Cove",
                            Region = "Northland",
                            SuitableBoardTypes = new List<string> { "Longboard", "Funboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("56e492f5-04ad-42b4-8b90-0091f36685fc"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "DoubleOverhead",
                            Description = "One of New Zealand's longest left-hand point breaks, near Ahipara at the foot of Ninety Mile Beach. Remote and raw — a reward for the committed.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Shipwreck Bay",
                            Region = "Northland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("2d8931ef-7b3c-480c-99c1-ac27f1f6df5f"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A dramatic black-sand beach tucked in a valley west of Auckland. Powerful beach break that rewards those who respect its conditions.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Bethells Beach",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("2cb08af2-836e-4f5e-a7e2-14aa572b68c4"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A hidden gem near Tutukaka in Northland. Sandy bottom beach break that rarely gets crowded — worth tracking down.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Sandy Bay",
                            Region = "Northland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("f60b983b-9353-4387-9917-7c058735b7f6"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A long, walling left-hand reef break near Oakura. One of Taranaki's most consistent and rewarding waves — best at solid swell with a light offshore.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Stent Road",
                            Region = "Taranaki",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("f4a5d3ca-048d-4905-9a93-8cf92fabc2b9"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A mellow reef break in Taranaki that turns on when other spots are too big. A local favourite that stays quiet even on good days.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Kumara Patch",
                            Region = "Taranaki",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("2e9d55ab-daf5-4141-94a2-d565db0db508"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "The main surf break in New Plymouth, breaking over a mix of reef and sand beneath the volcanic headland. Punchy and powerful when it lines up.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Back Beach",
                            Region = "Taranaki",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("78edcc0a-476c-4bd1-83ad-0471284eb0bc"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A reef break sitting just off Takapuna Beach on Auckland's North Shore. Can produce surprisingly good waves when the swell direction lines up.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Takapuna Reef",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("afe79384-de57-4288-bb89-362d08d3d6e4"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A lesser-known Auckland reef that rewards those in the know with uncrowded, hollow waves when conditions align. Worth checking on a small easterly swell.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "KneeHigh",
                            Name = "Daniels Reef",
                            Region = "Auckland",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("9eeb5861-d0bc-4cb9-84b3-f1174940ea7f"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "Beefy, strong, and occasionally rippable year-round beach break just north of Gisborne — most reliable from autumn to spring. At full tide the reef sections punch up. Stock Route, the short tubular runner on the south end, fires up on the right swell. One of the East Coast's most consistent waves.",
                            Facilities = new List<string> { "Bathrooms", "Lifeguard" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Wainui Beach",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("4d237b3e-7a1f-4a45-9935-8913929c5a7e"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A heavy point/reef break tucked below the Kaikoura mountains, named after the old freezing works nearby. Fast takeoffs into hollow sections over boulders and rocks — unpredictability increased post-2016 earthquake. Expert-only on larger swells; approach with local knowledge.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Meatworks",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("674759a2-93b5-4946-aa2f-237b42c7466c"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "The jewel in Kaikoura's surf crown — a long, peeling left-to-right bay break that fills the whole bay with some of the longest rides this side of Raglan. Steady offshore winds, incredible mountain views, and consistent winter swells from the east make this one of the South Island's most celebrated waves.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Mangamaunu",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Longboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("9aabf94d-fdaf-47e3-8616-e50123dd33c7"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A hidden bay east of Sumner with rocky headland rights that reward surfers willing to make the hike from the car park. One of Canterbury's most scenic and consistent breaks.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Taylor's Mistake",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("d49fe9f4-6e17-4a0b-a907-c529aef18fba"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A long, sandy stretch east of Whakatane with mellow beach break peaks and plenty of space. One of the Bay of Plenty's quietest surf beaches — ideal for beginners wanting room to learn.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "Lifeguard", "Campground" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Ohope Beach",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("96964eda-9754-4e3d-bf49-6a813e35f7f0"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A sheltered harbour-mouth beach break on the Coromandel's east coast that picks up east and northeast swells well. A reliable option when the west side is flat.",
                            Facilities = new List<string> { "Bathrooms", "SurfClub" },
                            MaxWaveSize = "WaistHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Tairua",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("222ea40c-6ba4-4b8c-b5d4-8a65f7e0702e"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Wellington's premier year-round surf beach, right beside the airport. Sand-bottomed peaks work for all levels at all times of year, with minimal localism — the friendliest lineup in the city. Fires best on calm mornings before the notorious afternoon northerly kicks in. Board hire and lessons available from the surf club.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard", "Rentals" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Lyall Bay",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Busy",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("37a14764-caad-42e5-8e6e-5240a8e9e378"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "A dramatic lighthouse bay on the Wairarapa coast, two hours from Wellington. A reef break that fires with powerful East Coast swells — the remote setting and iconic scenery make the drive very much worth it.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Castlepoint",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("57c0b8c7-6ecf-4cb8-8634-ce6da7b08d25"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A raw, wind-exposed beach break on Wellington's rugged west coast. Gets open-ocean swell that rarely reaches Lyall Bay — worth the extra drive when conditions align and the wind is light.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Makara Beach",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("e2c7acb6-000e-4933-b2b5-5f2a26f2a335"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Dunedin's iconic surf beach at the foot of the Otago Peninsula. Reliable Southern Ocean swells, a surf club that's been running for over a century, and a famous saltwater hot pool right on the beachfront.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard", "Rentals" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "St Clair Beach",
                            Region = "Otago",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("079ddd51-4279-453c-81af-b661e1a97f70"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Dunedin's quieter neighbour to St Clair, sharing the same reliable Southern Ocean swells on a long exposed beach with consistent peaks. A good choice when St Clair is too busy.",
                            Facilities = new List<string> { "Bathrooms", "SurfClub" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "St Kilda",
                            Region = "Otago",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("987dfab8-acc2-4dc1-b184-312374c9375d"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "A right-hand point break at the town end of Kaikoura, wrapping around the peninsula alongside the fur-seal colony. Mellower and more accessible than Mangamaunu further up the coast, with the town's cafes and gear hire close at hand.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Kaikoura Point",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("320f04de-34f7-4d2f-8a50-e6d079cf75ec"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A sheltered beach break south of Kaikoura town with low, easy-going waves ideal for novices. Protected from northerlies and shallow enough for foam boards — popular with surf schools on summer mornings. Arrive early to beat the crowds.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Okiwi Bay",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("1c35bc8a-9789-42a4-9bd4-368f5c774ec7"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "The closest break to Kaikoura town — a convenient option when you only have an hour to spare. Fun peaks go left and right on medium-swell days, and there's enough whitewash on smaller days for beginners. Nothing special, but reliably rideable.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Gooch's Beach",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("7c926dd3-e07d-496d-81d1-c4821e0546fb"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A beach and point break combo north of Kaikoura that improved noticeably after the 2016 earthquake. Best on bigger swells when both the beach and the point fill in — watch for the shallow shore break and stick to low tide on larger days. Dolphins are common.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Ward Beach",
                            Region = "Kaikoura",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("82d57d3e-60a4-48b6-bb65-dfb072918add"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Christchurch's most popular surf beach, stretching north from the famous pier. Consistent beach break peaks on most swells, full facilities, and a surf club that runs lessons — the go-to spot for the city.",
                            Facilities = new List<string> { "Bathrooms", "Showers", "SurfClub", "Lifeguard", "Rentals" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "New Brighton",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("25e8876b-5560-4052-9e23-8fa5bf034073"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "A long stretch of sand north of New Brighton with peaky, mellow waves that punch up on winter swells. A good escape when New Brighton gets crowded — shifting sandbanks keep conditions varied, and a local surf school operates here through summer.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Waimairi Beach",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("6c44f559-d734-4cf1-9a78-beba7b07cf7f"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A longboarder's dream about an hour south of Christchurch — a left-hand point off a boulder-dotted beach that produces some of the longest rides in the Canterbury region. Gets busy on solid south swells; arrive early for a smaller lineup.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Magnet Bay",
                            Region = "Christchurch",
                            SuitableBoardTypes = new List<string> { "Longboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("08ea9e93-ad99-4a50-8e38-5a16894a080a"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A wild beach break at the mouth of Otago Harbour with a genuine sense of isolation. The sandbars shift constantly and the Southern Ocean swells arrive unimpeded — rewarding for those willing to make the drive out to the peninsula.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Aramoana",
                            Region = "Otago",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("ffbb6992-3993-4712-b693-41412ec1cb2c"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "A raw reef break on the exposed southern edge of Dunedin, south of St Clair. Picks up more swell than anywhere else in the area and delivers punchy, hollow waves for those who venture this far — rarely crowded even on good days.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Blackhead",
                            Region = "Otago",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Quiet",
                            WaveType = "ReefBreak"
                        },
                        new
                        {
                            Id = new Guid("b428d363-06a3-42c1-bed6-4d6f50340717"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "A peeling left-hand point at the entrance to Wellington Harbour, working best on strong southerly swells through the winter months. A quieter alternative to Lyall Bay with a more committed paddle out — watch for the SW crosswind that can make it choppy in the afternoon.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Pencarrow Head",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Longboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("f06841b9-b3be-49db-82e9-8dec588e3207"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A dramatic south-facing bay in Wellington's western suburbs with a muscular right-hander point at its south end. A solid option when Lyall Bay is too crowded — the scenery is stunning and the waves have real character. Catches the same south swells as Lyall Bay.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Houghton Bay",
                            Region = "Wellington",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("cde176c8-1e45-457b-9b30-c1fd73561ea5"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "KneeHigh",
                            Description = "An uber-fun, accessible beach south of Gisborne with a mellow peeler that sections into glassy walls and frothing whitewash. Both a left and right point wrap around the bay, catching refracted south swells that can be smaller and cleaner than Wainui. Good for all levels on most days.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "AnkleHigh",
                            Name = "Sponge Bay",
                            Region = "Gisborne",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("6dfb9b90-fbed-49fa-9bf4-26b6f64027e0"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "The furthest and most rewarding of Raglan's three famous left-handers, a 20-minute walk from Whale Bay car park. Longer and more powerful than Manu Bay on a good swell, with a classic point-break shape that draws surfers from around the world.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Intermediate",
                            MinWaveSize = "WaistHigh",
                            Name = "Whale Bay",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Longboard", "Fish", "Shortboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("a69840d9-5d56-41f8-926b-efc39eb7363a"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "HeadHigh",
                            Description = "Heavy take-off and uber-fast hollow sections with seriously long rides. Two entry points: Outsides for those new to NZ lefts, Insides for the committed expert. Prized by locals and often considered the most rewarding of Raglan's three point breaks.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Advanced",
                            MinWaveSize = "WaistHigh",
                            Name = "Indicators",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish" },
                            TypicalCrowd = "Moderate",
                            WaveType = "PointBreak"
                        },
                        new
                        {
                            Id = new Guid("b9d233c7-01f7-48ba-b393-6ab66b91d936"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A consistent swell magnet about 35 minutes from Raglan town on black sand. Multiple peaks for all abilities on smaller days — shoulder-high and mellow at its best. A reliable alternative when Manu Bay and Whale Bay are too heavy.",
                            Facilities = new List<string>(),
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "KneeHigh",
                            Name = "Ruapuke Beach",
                            Region = "Waikato",
                            SuitableBoardTypes = new List<string> { "Rental", "Longboard", "Funboard", "Shortboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("80bc2dbd-50b6-4396-94a1-bc73a1ef9192"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "Famous for its thermal springs at low tide, Hot Water Beach also delivers solid beach-break surf when a decent easterly swell wraps in. Most visitors come for the springs, which means the water is often surprisingly uncrowded — arrive early and score both.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Hot Water Beach",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("6c8776eb-d2dc-485d-98dd-24558d15efc1"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A wild beach break beside the famous Pancake Rocks on the Paparoa coast. Raw Tasman Sea swells hit the black-sand beach with real power — almost never crowded, and the scenery is unlike anywhere else in New Zealand.",
                            Facilities = new List<string> { "Bathrooms" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Punakaiki",
                            Region = "WestCoast",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("bc88f11c-88ac-4fb1-ac5b-984488ff2800"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "The most accessible surf beach on the West Coast, right at the edge of Hokitika town. Consistent Tasman Sea swells break over dark sand with no crowds — the town's sunsets here are legendary, and the pounamu shops make the trip worthwhile rain or shine.",
                            Facilities = new List<string> { "Bathrooms", "SurfClub" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Hokitika Beach",
                            Region = "WestCoast",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("5de53267-9ae1-4c46-a3e8-3b7fcca20fd8"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A remote beach break on the East Cape road well north of Opotiki. Powerful, exposed swells hit the bay with little refraction, producing fast and hollow beach-break sections. The campground is basic but the waves — and the absence of crowds — are the whole point.",
                            Facilities = new List<string> { "Bathrooms", "Campground" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Waihau Bay",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Quiet",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("8e89b39f-4425-48ae-8a7b-4b0fc2313168"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A high-quality beach break southeast of Mount Maunganui that gets punchy and responsive on NE swells over two feet. Slightly fewer crowds than the Mount itself, a friendly local surf club with no localism, and fast shoulders on bigger sets. One of the Bay of Plenty's best-kept secrets.",
                            Facilities = new List<string> { "Bathrooms", "SurfClub" },
                            MaxWaveSize = "DoubleOverhead",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Papamoa Beach",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        },
                        new
                        {
                            Id = new Guid("5adf6b95-f296-4cd0-9178-24f0e16587ec"),
                            CreatedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentWaveSize = "WaistHigh",
                            Description = "A long beachfront strip south of Mount Maunganui main beach where waves lump up over the sandbars with fast drop-ins both left and right. Forgiving sand bottom, fewer swimmers than the Mount, and reliable shape on most NE swells — a great training ground for improving intermediates.",
                            Facilities = new List<string> { "Bathrooms", "Showers" },
                            MaxWaveSize = "HeadHigh",
                            MinSkillLevel = "Beginner",
                            MinWaveSize = "WaistHigh",
                            Name = "Tay Street",
                            Region = "BayOfPlenty",
                            SuitableBoardTypes = new List<string> { "Shortboard", "Fish", "Funboard" },
                            TypicalCrowd = "Moderate",
                            WaveType = "BeachBreak"
                        });
                });

            modelBuilder.Entity("Backend.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TikTokHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.UserPreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("BoardTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CrowdTolerance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PreferredFacilities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("PreferredRegions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("PreferredWaveSizes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("PreferredWaveTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Backend.Database.Entities.FavoriteEntity", b =>
                {
                    b.HasOne("Backend.Database.Entities.SurfSpotEntity", "Spot")
                        .WithMany("Favorites")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Entities.UserEntity", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSessionEntity", b =>
                {
                    b.HasOne("Backend.Database.Entities.SurfSpotEntity", "Spot")
                        .WithMany("SurfSessions")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Entities.UserEntity", "User")
                        .WithMany("SurfSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.UserPreferencesEntity", b =>
                {
                    b.HasOne("Backend.Database.Entities.UserEntity", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Backend.Database.Entities.UserPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Entities.SurfSpotEntity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("SurfSessions");
                });

            modelBuilder.Entity("Backend.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Preferences");

                    b.Navigation("SurfSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
